projects:
  ChecksAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: 64irox27ynhjzpq3lh4fe4z34e
        maxDepth: 2
extensions:
  amplify:
    version: 3
